# Format:  headline text, whether or not it should be considered healthcare related.
TESTCASES = [
    ("Fact Check: Video Does NOT Show Military Enforcement Of No-Fly Zone Over Antarctica",False),
    ("Fact Check: Photos Of Passport Do NOT Prove President Barack Obama Was Born In Kenya -- It was His Father\'s Passport",False),
    ("Fact Check: PCR Tests Do NOT Contain \'Magnetic Beacons\' Used For Tagging, Patenting Humans",True),
    ("Fact Check: Soursop, Beans, Tomatoes, Onions Will NOT Cure Cancer",True),
    ("Fact Check: Video Does NOT Show People Running From Real Zombies In US",False), 
    ("Facebook posts - HIV, the virus that can cause AIDS, is contagious. A video’s claim that it’s not is Pants on Fire!",True),
    ("Alliance Defending Freedom - Do 1 in 5 women suffer complications from abortion pills? No, group suing FDA shares flawed data",True),
    ("Facebook posts - Lead paint was banned to protect kids, not to expose them to radiation",True),
    ("Tweets - Kansas trans athlete law doesn’t 'authorize' genital inspections for kids, doesn’t ban them either",False),
    ("Cameron Sexton - Why it’s wrong to call the Tennessee state representatives insurrectionists",False),
    ("Fact Check: Video By Bitcoin Mining Company Riot Platforms Does NOT Prove Zero Carbon Emissions",False),
    ("Fact Check: Video Does NOT Show 'GWEN' Tower That Downloads Brainwaves",False),
    ("Fact Check: Joke Video Of 'Cloud Factory' At Chicago Ingredion Plant NOT Real",False),
    ("Fact Check: Man's Search For Birth Mom NOT Real -- It's Ruse To Get Shares, Harvest Personal Information",False),
    ("Facebook posts - A Facebook post suggests you fill out a form for a Nike gift card. Just … don’t do it",False),
    ("Facebook posts - Facebook post pushes claim about a slap that just doesn’t connect",False),
    ("Facebook posts - Digitized images are from a video game; they’re not from Ukraine war footage",False),
    ("Facebook posts - No evidence to support claims of FEMA camps for crimes against humanity arrestees",False),
    ("Facebook posts - Did Canada make it illegal to protest LGBTQ+ people? No, here’s what a proposed bill would do",False),
    ("Fact Check: Rep. Jim Jordan Did NOT Slap Robert Mueller During Testimony",False),
    ("Fact Check: Justin Bieber's Mother Did NOT Say Her Son Was Conceived As Result Of Rape In Her Autobiography",False),
    ("Fact Check: Video's Audio Does NOT Have Fallon Fox Speaking In Authentic Voice", False),
    ("Fact Check: Washington State Bill Does NOT Allow Government To Take Minor Children Away From Parents If They Refuse To Agree To Gender Transition Surgery", True),
    ("Fact Check: Usnea Lichen Is NOT Proven To Be More Effective Antibiotic Than Doxycycline and Penicillin", True),
    ("Fact Check: Radio Wave, Mobile Phone Technology Do NOT Cause Influenza, COVID Outbreaks", True),
]
